import { aeolianStarterPack } from './packs/aeolianStarter';
import { ionianStarterPack } from './packs/ionianStarter';
import { mixedStarterPack } from './packs/mixedStarter';
import type { ProgressionDefinition } from '../types/music';

const expandedProgressions: ProgressionDefinition[] = [
  {
    id: 'dorian_modal_pivot',
    lane: 'dorian',
    difficulty: 2,
    steps: [
      { roman: 'i7', functionTag: 'tonic', recommendedScaleIds: ['dorian', 'minor_pentatonic'], colorScaleIds: ['minor_blues'] },
      { roman: 'IV7', functionTag: 'color', recommendedScaleIds: ['mixolydian'], colorScaleIds: ['dorian'] },
      { roman: 'bIIImaj7', functionTag: 'color', recommendedScaleIds: ['ionian', 'major_pentatonic'], colorScaleIds: ['lydian'] },
      { roman: 'i7', functionTag: 'tonic', recommendedScaleIds: ['dorian'], colorScaleIds: ['minor_pentatonic'] },
    ],
    allowedVoicings: ['shell_137', 'closed_7th', 'inversion_1'],
    rhythmPlan: ['block_whole', 'charleston', 'quarters', 'charleston'],
    maxVoiceMotionSemitones: 7,
    tonicCenterStable: true,
    tags: {
      styles: ['modal_jazz', 'contemporary_modal'],
      modeFamilies: ['dorian', 'mixolydian', 'ionian'],
      families: ['modal_vamp', 'cadence'],
    },
    difficultyProfile: {
      level: 2,
      accidentalComplexity: 2,
      borrowedChordCount: 0,
      alterationComplexity: 0,
    },
    chainTargets: ['dorian_chain_release'],
  },
  {
    id: 'dorian_chain_release',
    lane: 'dorian',
    difficulty: 2,
    steps: [
      { roman: 'i7', functionTag: 'tonic', recommendedScaleIds: ['dorian'], colorScaleIds: ['minor_pentatonic'] },
      { roman: 'ii7', functionTag: 'predominant', recommendedScaleIds: ['dorian'], colorScaleIds: ['major_pentatonic'] },
      { roman: 'bVII7', functionTag: 'dominant', recommendedScaleIds: ['mixolydian'], colorScaleIds: ['major_blues'] },
      { roman: 'i7', functionTag: 'tonic', recommendedScaleIds: ['dorian'], colorScaleIds: ['minor_blues'] },
    ],
    allowedVoicings: ['shell_137', 'closed_7th', 'inversion_1'],
    rhythmPlan: ['quarters', 'charleston', 'charleston', 'block_whole'],
    maxVoiceMotionSemitones: 8,
    tonicCenterStable: true,
    tags: {
      styles: ['modal_jazz', 'contemporary_modal'],
      modeFamilies: ['dorian', 'mixolydian'],
      families: ['modal_vamp', 'turnaround'],
    },
    difficultyProfile: {
      level: 2,
      accidentalComplexity: 2,
      borrowedChordCount: 0,
      alterationComplexity: 0,
    },
    chainTargets: ['dorian_modal_pivot', 'mixolydian_dominant_vamp'],
  },
  {
    id: 'lydian_bright_lift',
    lane: 'lydian',
    difficulty: 2,
    steps: [
      { roman: 'Imaj7', functionTag: 'tonic', recommendedScaleIds: ['lydian'], colorScaleIds: ['major_pentatonic'] },
      { roman: 'II7', functionTag: 'color', recommendedScaleIds: ['lydian_dominant'], colorScaleIds: ['mixolydian'] },
      { roman: 'Vmaj7', functionTag: 'color', recommendedScaleIds: ['ionian'], colorScaleIds: ['lydian'] },
      { roman: 'Imaj7', functionTag: 'tonic', recommendedScaleIds: ['lydian'], colorScaleIds: ['major_pentatonic'] },
    ],
    allowedVoicings: ['shell_137', 'closed_7th', 'inversion_1'],
    rhythmPlan: ['block_whole', 'quarters', 'charleston', 'block_whole'],
    maxVoiceMotionSemitones: 8,
    tonicCenterStable: true,
    tags: {
      styles: ['modal_jazz', 'contemporary_modal'],
      modeFamilies: ['lydian', 'ionian', 'mixolydian'],
      families: ['modal_vamp', 'circle_motion'],
    },
    difficultyProfile: {
      level: 2,
      accidentalComplexity: 2,
      borrowedChordCount: 0,
      alterationComplexity: 1,
    },
    chainTargets: ['mixolydian_dominant_vamp'],
  },
  {
    id: 'mixolydian_dominant_vamp',
    lane: 'mixolydian',
    difficulty: 2,
    steps: [
      { roman: 'I7', functionTag: 'tonic', recommendedScaleIds: ['mixolydian', 'major_blues'], colorScaleIds: ['major_pentatonic'] },
      { roman: 'bVIImaj7', functionTag: 'color', recommendedScaleIds: ['lydian'], colorScaleIds: ['ionian'] },
      { roman: 'IV7', functionTag: 'predominant', recommendedScaleIds: ['mixolydian'], colorScaleIds: ['major_blues'] },
      { roman: 'I7', functionTag: 'tonic', recommendedScaleIds: ['mixolydian'], colorScaleIds: ['major_pentatonic'] },
    ],
    allowedVoicings: ['shell_137', 'closed_7th', 'inversion_1'],
    rhythmPlan: ['charleston', 'charleston', 'quarters', 'block_whole'],
    maxVoiceMotionSemitones: 8,
    tonicCenterStable: true,
    tags: {
      styles: ['modal_jazz', 'contemporary_modal'],
      modeFamilies: ['mixolydian', 'lydian', 'ionian'],
      families: ['modal_vamp', 'dominant_cycle'],
    },
    difficultyProfile: {
      level: 2,
      accidentalComplexity: 2,
      borrowedChordCount: 1,
      alterationComplexity: 0,
    },
    chainTargets: ['secondary_dominant_chain', 'lydian_dominant_resolve'],
  },
  {
    id: 'phrygian_pedal_turn',
    lane: 'phrygian',
    difficulty: 2,
    steps: [
      { roman: 'i7', functionTag: 'tonic', recommendedScaleIds: ['phrygian'], colorScaleIds: ['minor_blues'] },
      { roman: 'bIImaj7', functionTag: 'color', recommendedScaleIds: ['lydian'], colorScaleIds: ['major_pentatonic'] },
      { roman: 'bVII7', functionTag: 'dominant', recommendedScaleIds: ['mixolydian'], colorScaleIds: ['phrygian'] },
      { roman: 'i7', functionTag: 'tonic', recommendedScaleIds: ['phrygian'], colorScaleIds: ['minor_pentatonic'] },
    ],
    allowedVoicings: ['shell_137', 'closed_7th'],
    rhythmPlan: ['block_whole', 'quarters', 'quarters', 'block_whole'],
    maxVoiceMotionSemitones: 8,
    tonicCenterStable: true,
    tags: {
      styles: ['modal_jazz', 'contemporary_modal'],
      modeFamilies: ['phrygian', 'lydian', 'mixolydian'],
      families: ['modal_vamp', 'minor_loop'],
    },
    difficultyProfile: {
      level: 2,
      accidentalComplexity: 3,
      borrowedChordCount: 1,
      alterationComplexity: 0,
    },
    chainTargets: ['harmonic_minor_cadence'],
  },
  {
    id: 'harmonic_minor_cadence',
    lane: 'aeolian',
    difficulty: 3,
    steps: [
      { roman: 'iiø', functionTag: 'predominant', recommendedScaleIds: ['locrian_natural_2'], colorScaleIds: ['harmonic_minor'] },
      { roman: 'V7', functionTag: 'dominant', recommendedScaleIds: ['phrygian_dominant'], colorScaleIds: ['altered'] },
      { roman: 'i7', functionTag: 'tonic', recommendedScaleIds: ['harmonic_minor', 'minor_pentatonic'], colorScaleIds: ['melodic_minor'] },
      { roman: 'iv7', functionTag: 'predominant', recommendedScaleIds: ['dorian_b2'], colorScaleIds: ['harmonic_minor'] },
    ],
    allowedVoicings: ['closed_7th', 'inversion_1', 'shell_137'],
    rhythmPlan: ['quarters', 'charleston', 'block_whole', 'quarters'],
    maxVoiceMotionSemitones: 9,
    tonicCenterStable: true,
    tags: {
      styles: ['functional_jazz', 'contemporary_modal'],
      modeFamilies: ['aeolian', 'mixolydian', 'phrygian'],
      families: ['cadence', 'minor_loop'],
    },
    difficultyProfile: {
      level: 3,
      accidentalComplexity: 3,
      borrowedChordCount: 0,
      alterationComplexity: 2,
    },
    chainTargets: ['melodic_minor_float', 'locrian_natural_two_gate'],
  },
  {
    id: 'melodic_minor_float',
    lane: 'aeolian',
    difficulty: 3,
    steps: [
      { roman: 'i7', functionTag: 'tonic', recommendedScaleIds: ['melodic_minor'], colorScaleIds: ['harmonic_minor'] },
      { roman: 'II7', functionTag: 'color', recommendedScaleIds: ['lydian_augmented'], colorScaleIds: ['lydian_dominant'] },
      { roman: 'V7', functionTag: 'dominant', recommendedScaleIds: ['altered'], colorScaleIds: ['lydian_dominant'] },
      { roman: 'i7', functionTag: 'tonic', recommendedScaleIds: ['melodic_minor'], colorScaleIds: ['minor_blues'] },
    ],
    allowedVoicings: ['closed_7th', 'inversion_1'],
    rhythmPlan: ['block_whole', 'quarters', 'charleston', 'block_whole'],
    maxVoiceMotionSemitones: 9,
    tonicCenterStable: true,
    tags: {
      styles: ['functional_jazz', 'contemporary_modal'],
      modeFamilies: ['aeolian', 'lydian', 'mixolydian'],
      families: ['cadence', 'turnaround'],
    },
    difficultyProfile: {
      level: 3,
      accidentalComplexity: 4,
      borrowedChordCount: 0,
      alterationComplexity: 2,
    },
    chainTargets: ['secondary_dominant_chain'],
  },
  {
    id: 'locrian_natural_two_gate',
    lane: 'aeolian',
    difficulty: 3,
    steps: [
      { roman: 'iiø', functionTag: 'passing', recommendedScaleIds: ['locrian_natural_2'], colorScaleIds: ['locrian'] },
      { roman: 'bIIImaj7', functionTag: 'color', recommendedScaleIds: ['lydian_augmented'], colorScaleIds: ['ionian'] },
      { roman: 'V7', functionTag: 'dominant', recommendedScaleIds: ['altered'], colorScaleIds: ['phrygian_dominant'] },
      { roman: 'i7', functionTag: 'tonic', recommendedScaleIds: ['harmonic_minor'], colorScaleIds: ['melodic_minor'] },
    ],
    allowedVoicings: ['closed_7th', 'inversion_1'],
    rhythmPlan: ['quarters', 'quarters', 'charleston', 'block_whole'],
    maxVoiceMotionSemitones: 9,
    tonicCenterStable: true,
    tags: {
      styles: ['functional_jazz'],
      modeFamilies: ['aeolian', 'ionian', 'mixolydian'],
      families: ['cadence', 'turnaround'],
    },
    difficultyProfile: {
      level: 3,
      accidentalComplexity: 4,
      borrowedChordCount: 1,
      alterationComplexity: 2,
    },
    chainTargets: ['harmonic_minor_cadence'],
  },
  {
    id: 'secondary_dominant_chain',
    lane: 'mixolydian',
    difficulty: 3,
    steps: [
      { roman: 'VI7', functionTag: 'dominant', recommendedScaleIds: ['mixolydian', 'major_blues'], colorScaleIds: ['lydian_dominant'] },
      { roman: 'II7', functionTag: 'dominant', recommendedScaleIds: ['lydian_dominant'], colorScaleIds: ['whole_tone'] },
      { roman: 'V7', functionTag: 'dominant', recommendedScaleIds: ['altered'], colorScaleIds: ['half_whole_diminished'] },
      { roman: 'Imaj7', functionTag: 'tonic', recommendedScaleIds: ['ionian', 'lydian'], colorScaleIds: ['major_pentatonic'] },
    ],
    allowedVoicings: ['closed_7th', 'inversion_1', 'shell_137'],
    rhythmPlan: ['quarters', 'quarters', 'charleston', 'block_whole'],
    maxVoiceMotionSemitones: 9,
    tonicCenterStable: true,
    tags: {
      styles: ['functional_jazz'],
      modeFamilies: ['mixolydian', 'ionian', 'lydian'],
      families: ['secondary_dominant', 'dominant_cycle', 'cadence'],
    },
    difficultyProfile: {
      level: 3,
      accidentalComplexity: 3,
      borrowedChordCount: 0,
      alterationComplexity: 2,
    },
    chainTargets: ['altered_backcycle', 'whole_tone_drift'],
  },
  {
    id: 'lydian_dominant_resolve',
    lane: 'mixolydian',
    difficulty: 3,
    steps: [
      { roman: 'II7', functionTag: 'color', recommendedScaleIds: ['lydian_dominant'], colorScaleIds: ['whole_tone'] },
      { roman: 'V7', functionTag: 'dominant', recommendedScaleIds: ['mixolydian_b6'], colorScaleIds: ['altered'] },
      { roman: 'Imaj7', functionTag: 'tonic', recommendedScaleIds: ['lydian'], colorScaleIds: ['ionian'] },
      { roman: 'VI7', functionTag: 'dominant', recommendedScaleIds: ['mixolydian'], colorScaleIds: ['major_blues'] },
    ],
    allowedVoicings: ['closed_7th', 'inversion_1'],
    rhythmPlan: ['charleston', 'charleston', 'block_whole', 'quarters'],
    maxVoiceMotionSemitones: 9,
    tonicCenterStable: true,
    tags: {
      styles: ['functional_jazz', 'contemporary_modal'],
      modeFamilies: ['mixolydian', 'lydian', 'ionian'],
      families: ['dominant_cycle', 'cadence'],
    },
    difficultyProfile: {
      level: 3,
      accidentalComplexity: 4,
      borrowedChordCount: 0,
      alterationComplexity: 2,
    },
    chainTargets: ['secondary_dominant_chain'],
  },
  {
    id: 'altered_backcycle',
    lane: 'mixolydian',
    difficulty: 4,
    steps: [
      { roman: 'bII7', functionTag: 'dominant', recommendedScaleIds: ['altered'], colorScaleIds: ['half_whole_diminished'] },
      { roman: 'V7', functionTag: 'dominant', recommendedScaleIds: ['altered'], colorScaleIds: ['whole_tone'] },
      { roman: 'Imaj7', functionTag: 'tonic', recommendedScaleIds: ['ionian'], colorScaleIds: ['lydian'] },
      { roman: 'bVII7', functionTag: 'dominant', recommendedScaleIds: ['lydian_dominant'], colorScaleIds: ['mixolydian'] },
    ],
    allowedVoicings: ['closed_7th', 'inversion_1'],
    rhythmPlan: ['quarters', 'charleston', 'block_whole', 'quarters'],
    maxVoiceMotionSemitones: 10,
    tonicCenterStable: false,
    tags: {
      styles: ['functional_jazz'],
      modeFamilies: ['mixolydian', 'ionian', 'lydian'],
      families: ['dominant_cycle', 'backdoor'],
    },
    difficultyProfile: {
      level: 4,
      accidentalComplexity: 4,
      borrowedChordCount: 1,
      alterationComplexity: 3,
    },
    chainTargets: ['whole_tone_drift', 'half_whole_dominant_cycle'],
  },
  {
    id: 'tritone_sub_cadence',
    lane: 'mixolydian',
    difficulty: 3,
    steps: [
      { roman: 'ii7', functionTag: 'predominant', recommendedScaleIds: ['dorian'], colorScaleIds: ['major_pentatonic'] },
      { roman: 'bII7', functionTag: 'dominant', recommendedScaleIds: ['lydian_dominant'], colorScaleIds: ['altered'] },
      { roman: 'Imaj7', functionTag: 'tonic', recommendedScaleIds: ['ionian'], colorScaleIds: ['lydian'] },
      { roman: 'VI7', functionTag: 'dominant', recommendedScaleIds: ['mixolydian'], colorScaleIds: ['lydian_dominant'] },
    ],
    allowedVoicings: ['closed_7th', 'inversion_1', 'shell_137'],
    rhythmPlan: ['quarters', 'charleston', 'block_whole', 'quarters'],
    maxVoiceMotionSemitones: 9,
    tonicCenterStable: false,
    tags: {
      styles: ['functional_jazz'],
      modeFamilies: ['mixolydian', 'ionian', 'lydian'],
      families: ['cadence', 'dominant_cycle'],
    },
    difficultyProfile: {
      level: 3,
      accidentalComplexity: 4,
      borrowedChordCount: 1,
      alterationComplexity: 2,
    },
    chainTargets: ['secondary_dominant_chain', 'altered_backcycle'],
  },
  {
    id: 'phrygian_dominant_minor_gate',
    lane: 'mixolydian',
    difficulty: 4,
    steps: [
      { roman: 'V7', functionTag: 'dominant', recommendedScaleIds: ['phrygian_dominant'], colorScaleIds: ['altered'] },
      { roman: 'i7', functionTag: 'tonic', recommendedScaleIds: ['harmonic_minor'], colorScaleIds: ['melodic_minor'] },
      { roman: 'bVII7', functionTag: 'dominant', recommendedScaleIds: ['mixolydian_b6'], colorScaleIds: ['half_whole_diminished'] },
      { roman: 'i7', functionTag: 'tonic', recommendedScaleIds: ['harmonic_minor'], colorScaleIds: ['minor_blues'] },
    ],
    allowedVoicings: ['closed_7th', 'shell_137'],
    rhythmPlan: ['charleston', 'block_whole', 'quarters', 'block_whole'],
    maxVoiceMotionSemitones: 10,
    tonicCenterStable: true,
    tags: {
      styles: ['functional_jazz', 'contemporary_modal'],
      modeFamilies: ['mixolydian', 'aeolian', 'phrygian'],
      families: ['cadence', 'dominant_cycle', 'minor_loop'],
    },
    difficultyProfile: {
      level: 4,
      accidentalComplexity: 4,
      borrowedChordCount: 0,
      alterationComplexity: 3,
    },
    chainTargets: ['harmonic_minor_cadence'],
  },
  {
    id: 'whole_tone_drift',
    lane: 'mixolydian',
    difficulty: 4,
    steps: [
      { roman: 'I7', functionTag: 'tonic', recommendedScaleIds: ['whole_tone'], colorScaleIds: ['lydian_dominant'] },
      { roman: 'III7', functionTag: 'color', recommendedScaleIds: ['whole_tone'], colorScaleIds: ['half_whole_diminished'] },
      { roman: 'bVI7', functionTag: 'dominant', recommendedScaleIds: ['whole_tone'], colorScaleIds: ['altered'] },
      { roman: 'I7', functionTag: 'tonic', recommendedScaleIds: ['whole_tone'], colorScaleIds: ['major_blues'] },
    ],
    allowedVoicings: ['closed_7th', 'inversion_1'],
    rhythmPlan: ['block_whole', 'quarters', 'quarters', 'block_whole'],
    maxVoiceMotionSemitones: 10,
    tonicCenterStable: false,
    tags: {
      styles: ['contemporary_modal'],
      modeFamilies: ['mixolydian'],
      families: ['symmetric_color', 'dominant_cycle'],
    },
    difficultyProfile: {
      level: 4,
      accidentalComplexity: 5,
      borrowedChordCount: 0,
      alterationComplexity: 3,
    },
    chainTargets: ['half_whole_dominant_cycle'],
  },
  {
    id: 'half_whole_dominant_cycle',
    lane: 'mixolydian',
    difficulty: 4,
    steps: [
      { roman: 'V7', functionTag: 'dominant', recommendedScaleIds: ['half_whole_diminished'], colorScaleIds: ['altered'] },
      { roman: 'bII7', functionTag: 'dominant', recommendedScaleIds: ['half_whole_diminished'], colorScaleIds: ['whole_tone'] },
      { roman: 'Imaj7', functionTag: 'tonic', recommendedScaleIds: ['ionian'], colorScaleIds: ['lydian'] },
      { roman: 'VI7', functionTag: 'dominant', recommendedScaleIds: ['half_whole_diminished'], colorScaleIds: ['mixolydian'] },
    ],
    allowedVoicings: ['closed_7th', 'inversion_1'],
    rhythmPlan: ['quarters', 'quarters', 'block_whole', 'charleston'],
    maxVoiceMotionSemitones: 10,
    tonicCenterStable: false,
    tags: {
      styles: ['functional_jazz', 'contemporary_modal'],
      modeFamilies: ['mixolydian', 'ionian', 'lydian'],
      families: ['symmetric_color', 'dominant_cycle', 'cadence'],
    },
    difficultyProfile: {
      level: 4,
      accidentalComplexity: 5,
      borrowedChordCount: 1,
      alterationComplexity: 3,
    },
    chainTargets: ['whole_half_release', 'secondary_dominant_chain'],
  },
  {
    id: 'whole_half_release',
    lane: 'aeolian',
    difficulty: 4,
    steps: [
      { roman: 'iiø', functionTag: 'passing', recommendedScaleIds: ['whole_half_diminished'], colorScaleIds: ['locrian_natural_2'] },
      { roman: 'V7', functionTag: 'dominant', recommendedScaleIds: ['half_whole_diminished'], colorScaleIds: ['altered'] },
      { roman: 'i7', functionTag: 'tonic', recommendedScaleIds: ['harmonic_minor'], colorScaleIds: ['melodic_minor'] },
      { roman: 'bVImaj7', functionTag: 'color', recommendedScaleIds: ['lydian_augmented'], colorScaleIds: ['major_pentatonic'] },
    ],
    allowedVoicings: ['closed_7th', 'inversion_1'],
    rhythmPlan: ['quarters', 'charleston', 'block_whole', 'quarters'],
    maxVoiceMotionSemitones: 10,
    tonicCenterStable: true,
    tags: {
      styles: ['functional_jazz', 'contemporary_modal'],
      modeFamilies: ['aeolian', 'ionian', 'lydian'],
      families: ['symmetric_color', 'cadence'],
    },
    difficultyProfile: {
      level: 4,
      accidentalComplexity: 5,
      borrowedChordCount: 1,
      alterationComplexity: 3,
    },
    chainTargets: ['harmonic_minor_cadence', 'whole_tone_drift'],
  },
];

export const PROGRESSION_LIBRARY: ProgressionDefinition[] = [
  ...ionianStarterPack.progressions,
  ...aeolianStarterPack.progressions,
  ...mixedStarterPack.progressions,
  ...expandedProgressions,
];
