import type { ScaleFamilyId, ScaleId, ScaleOption } from '../types/music';

export const SCALE_LIBRARY: Record<ScaleId, ScaleOption> = {
  ionian: {
    id: 'ionian',
    label: 'Ionian',
    category: 'mode',
    familyId: 'diatonic_modes',
    intervalFormula: ['1', '2', '3', '4', '5', '6', '7'],
    qualityTags: ['major', 'stable'],
  },
  dorian: {
    id: 'dorian',
    label: 'Dorian',
    category: 'mode',
    familyId: 'diatonic_modes',
    intervalFormula: ['1', '2', 'b3', '4', '5', '6', 'b7'],
    qualityTags: ['minor', 'modal'],
  },
  phrygian: {
    id: 'phrygian',
    label: 'Phrygian',
    category: 'mode',
    familyId: 'diatonic_modes',
    intervalFormula: ['1', 'b2', 'b3', '4', '5', 'b6', 'b7'],
    qualityTags: ['minor', 'color'],
  },
  lydian: {
    id: 'lydian',
    label: 'Lydian',
    category: 'mode',
    familyId: 'diatonic_modes',
    intervalFormula: ['1', '2', '3', '#4', '5', '6', '7'],
    qualityTags: ['major', 'bright'],
  },
  mixolydian: {
    id: 'mixolydian',
    label: 'Mixolydian',
    category: 'mode',
    familyId: 'diatonic_modes',
    intervalFormula: ['1', '2', '3', '4', '5', '6', 'b7'],
    qualityTags: ['dominant', 'functional'],
  },
  aeolian: {
    id: 'aeolian',
    label: 'Aeolian',
    category: 'mode',
    familyId: 'diatonic_modes',
    intervalFormula: ['1', '2', 'b3', '4', '5', 'b6', 'b7'],
    qualityTags: ['minor', 'stable'],
  },
  locrian: {
    id: 'locrian',
    label: 'Locrian',
    category: 'mode',
    familyId: 'diatonic_modes',
    intervalFormula: ['1', 'b2', 'b3', '4', 'b5', 'b6', 'b7'],
    qualityTags: ['half_diminished', 'tense'],
  },
  major_pentatonic: {
    id: 'major_pentatonic',
    label: 'Major Pentatonic',
    category: 'pentatonic',
    familyId: 'pentatonic_blues',
    intervalFormula: ['1', '2', '3', '5', '6'],
    qualityTags: ['major', 'inside'],
  },
  minor_pentatonic: {
    id: 'minor_pentatonic',
    label: 'Minor Pentatonic',
    category: 'pentatonic',
    familyId: 'pentatonic_blues',
    intervalFormula: ['1', 'b3', '4', '5', 'b7'],
    qualityTags: ['minor', 'inside'],
  },
  major_blues: {
    id: 'major_blues',
    label: 'Major Blues',
    category: 'blues',
    familyId: 'pentatonic_blues',
    intervalFormula: ['1', '2', 'b3', '3', '5', '6'],
    qualityTags: ['major', 'blues'],
  },
  minor_blues: {
    id: 'minor_blues',
    label: 'Minor Blues',
    category: 'blues',
    familyId: 'pentatonic_blues',
    intervalFormula: ['1', 'b3', '4', 'b5', '5', 'b7'],
    qualityTags: ['minor', 'blues'],
  },
  harmonic_minor: {
    id: 'harmonic_minor',
    label: 'Harmonic Minor',
    category: 'minor_system',
    familyId: 'harmonic_minor_family',
    intervalFormula: ['1', '2', 'b3', '4', '5', 'b6', '7'],
    qualityTags: ['minor', 'functional'],
  },
  phrygian_dominant: {
    id: 'phrygian_dominant',
    label: 'Phrygian Dominant',
    category: 'dominant_color',
    familyId: 'harmonic_minor_family',
    intervalFormula: ['1', 'b2', '3', '4', '5', 'b6', 'b7'],
    qualityTags: ['dominant', 'exotic'],
  },
  melodic_minor: {
    id: 'melodic_minor',
    label: 'Melodic Minor',
    category: 'minor_system',
    familyId: 'melodic_minor_family',
    intervalFormula: ['1', '2', 'b3', '4', '5', '6', '7'],
    qualityTags: ['minor', 'modern'],
  },
  dorian_b2: {
    id: 'dorian_b2',
    label: 'Dorian b2',
    category: 'minor_system',
    familyId: 'melodic_minor_family',
    intervalFormula: ['1', 'b2', 'b3', '4', '5', '6', 'b7'],
    qualityTags: ['minor', 'dark'],
  },
  lydian_augmented: {
    id: 'lydian_augmented',
    label: 'Lydian Augmented',
    category: 'dominant_color',
    familyId: 'melodic_minor_family',
    intervalFormula: ['1', '2', '3', '#4', '#5', '6', '7'],
    qualityTags: ['major', 'augmented'],
  },
  lydian_dominant: {
    id: 'lydian_dominant',
    label: 'Lydian Dominant',
    category: 'dominant_color',
    familyId: 'dominant_altered_family',
    intervalFormula: ['1', '2', '3', '#4', '5', '6', 'b7'],
    qualityTags: ['dominant', 'bright'],
  },
  mixolydian_b6: {
    id: 'mixolydian_b6',
    label: 'Mixolydian b6',
    category: 'dominant_color',
    familyId: 'melodic_minor_family',
    intervalFormula: ['1', '2', '3', '4', '5', 'b6', 'b7'],
    qualityTags: ['dominant', 'minor_color'],
  },
  locrian_natural_2: {
    id: 'locrian_natural_2',
    label: 'Locrian Natural 2',
    category: 'minor_system',
    familyId: 'melodic_minor_family',
    intervalFormula: ['1', '2', 'b3', '4', 'b5', 'b6', 'b7'],
    qualityTags: ['half_diminished', 'functional'],
  },
  altered: {
    id: 'altered',
    label: 'Altered',
    category: 'dominant_color',
    familyId: 'dominant_altered_family',
    intervalFormula: ['1', 'b2', '#2', '3', 'b5', '#5', 'b7'],
    qualityTags: ['dominant', 'altered'],
  },
  whole_tone: {
    id: 'whole_tone',
    label: 'Whole Tone',
    category: 'symmetric',
    familyId: 'symmetric_family',
    intervalFormula: ['1', '2', '3', '#4', '#5', 'b7'],
    qualityTags: ['dominant', 'symmetric'],
  },
  half_whole_diminished: {
    id: 'half_whole_diminished',
    label: 'Half-Whole Diminished',
    category: 'symmetric',
    familyId: 'symmetric_family',
    intervalFormula: ['1', 'b2', '#2', '3', '#4', '5', '6', 'b7'],
    qualityTags: ['dominant', 'symmetric'],
  },
  whole_half_diminished: {
    id: 'whole_half_diminished',
    label: 'Whole-Half Diminished',
    category: 'symmetric',
    familyId: 'symmetric_family',
    intervalFormula: ['1', '2', 'b3', '4', 'b5', 'b6', '6', '7'],
    qualityTags: ['diminished', 'symmetric'],
  },
};

export function getScaleOption(scaleId: ScaleId): ScaleOption {
  return SCALE_LIBRARY[scaleId];
}

export function scaleFamilyForScaleId(scaleId: ScaleId): ScaleFamilyId {
  return getScaleOption(scaleId).familyId;
}
