import type { ContentPack } from './types';

export const aeolianStarterPack: ContentPack = {
  id: 'aeolian_starter_v1',
  version: 1,
  lane: 'aeolian',
  roots: ['A', 'E', 'D'],
  voicings: ['shell_137', 'closed_7th', 'inversion_1'],
  rhythms: ['block_whole', 'quarters', 'charleston'],
  templates: [
    {
      id: 'aeolian_b67_loop',
      lane: 'aeolian',
      difficulty: 1,
      romanPlan: ['i7', 'bVII7', 'bVImaj7', 'bVII7'],
      allowedVoicings: ['shell_137', 'closed_7th'],
      rhythmPlan: ['block_whole', 'block_whole', 'block_whole', 'block_whole'],
      maxVoiceMotionSemitones: 6,
      tonicCenterStable: true,
    },
    {
      id: 'aeolian_iv_bVII',
      lane: 'aeolian',
      difficulty: 1,
      romanPlan: ['i7', 'iv7', 'bVII7', 'bIIImaj7'],
      allowedVoicings: ['shell_137', 'closed_7th', 'inversion_1'],
      rhythmPlan: ['charleston', 'charleston', 'charleston', 'charleston'],
      maxVoiceMotionSemitones: 7,
      tonicCenterStable: true,
    },
    {
      id: 'aeolian_bVI_bIII',
      lane: 'aeolian',
      difficulty: 1,
      romanPlan: ['i7', 'bVImaj7', 'bIIImaj7', 'bVII7'],
      allowedVoicings: ['shell_137', 'closed_7th'],
      rhythmPlan: ['quarters', 'quarters', 'quarters', 'quarters'],
      maxVoiceMotionSemitones: 7,
      tonicCenterStable: true,
    },
    {
      id: 'aeolian_scalar_lane',
      lane: 'aeolian',
      difficulty: 2,
      romanPlan: ['i7', 'iiø', 'bIIImaj7', 'iv7'],
      allowedVoicings: ['shell_137', 'closed_7th', 'inversion_1'],
      rhythmPlan: ['block_whole', 'charleston', 'charleston', 'quarters'],
      maxVoiceMotionSemitones: 8,
      tonicCenterStable: true,
    },
    {
      id: 'aeolian_minor_turn',
      lane: 'aeolian',
      difficulty: 2,
      romanPlan: ['iv7', 'v7', 'bVImaj7', 'bVII7'],
      allowedVoicings: ['shell_137', 'closed_7th', 'inversion_1'],
      rhythmPlan: ['charleston', 'quarters', 'quarters', 'charleston'],
      maxVoiceMotionSemitones: 9,
      tonicCenterStable: true,
    },
    {
      id: 'aeolian_return_home',
      lane: 'aeolian',
      difficulty: 2,
      romanPlan: ['bIIImaj7', 'bVII7', 'i7', 'iv7'],
      allowedVoicings: ['closed_7th', 'inversion_1'],
      rhythmPlan: ['quarters', 'charleston', 'block_whole', 'quarters'],
      maxVoiceMotionSemitones: 9,
      tonicCenterStable: true,
    },
  ],
};
