import type { ContentPack } from './types';

export const aeolianStarterPack: ContentPack = {
  id: 'aeolian_starter_v1',
  version: 1,
  lane: 'aeolian',
  roots: ['A', 'E', 'D'],
  voicings: ['shell_137', 'closed_7th', 'inversion_1'],
  rhythms: ['block_whole', 'quarters', 'charleston'],
  progressions: [
    {
      id: 'aeolian_b67_loop',
      lane: 'aeolian',
      difficulty: 1,
      steps: [
        { roman: 'i7', functionTag: 'tonic', recommendedScaleIds: ['aeolian', 'minor_pentatonic'], colorScaleIds: ['dorian'] },
        { roman: 'bVII7', functionTag: 'dominant', recommendedScaleIds: ['mixolydian'], colorScaleIds: ['aeolian'] },
        { roman: 'bVImaj7', functionTag: 'color', recommendedScaleIds: ['lydian', 'major_pentatonic'], colorScaleIds: ['ionian'] },
        { roman: 'bVII7', functionTag: 'dominant', recommendedScaleIds: ['mixolydian'], colorScaleIds: ['aeolian'] },
      ],
      allowedVoicings: ['shell_137', 'closed_7th'],
      rhythmPlan: ['block_whole', 'block_whole', 'block_whole', 'block_whole'],
      maxVoiceMotionSemitones: 6,
      tonicCenterStable: true,
      tags: {
        styles: ['modal_jazz', 'contemporary_modal'],
        modeFamilies: ['aeolian', 'mixolydian', 'lydian'],
        families: ['minor_loop'],
      },
      difficultyProfile: {
        level: 1,
        accidentalComplexity: 1,
        borrowedChordCount: 0,
        alterationComplexity: 0,
      },
      chainTargets: ['aeolian_return_home'],
    },
    {
      id: 'aeolian_iv_bVII',
      lane: 'aeolian',
      difficulty: 1,
      steps: [
        { roman: 'i7', functionTag: 'tonic', recommendedScaleIds: ['aeolian', 'minor_pentatonic'], colorScaleIds: ['dorian'] },
        { roman: 'iv7', functionTag: 'predominant', recommendedScaleIds: ['dorian'], colorScaleIds: ['aeolian'] },
        { roman: 'bVII7', functionTag: 'dominant', recommendedScaleIds: ['mixolydian'], colorScaleIds: ['aeolian'] },
        { roman: 'bIIImaj7', functionTag: 'color', recommendedScaleIds: ['ionian', 'major_pentatonic'], colorScaleIds: ['lydian'] },
      ],
      allowedVoicings: ['shell_137', 'closed_7th', 'inversion_1'],
      rhythmPlan: ['charleston', 'charleston', 'charleston', 'charleston'],
      maxVoiceMotionSemitones: 7,
      tonicCenterStable: true,
      tags: {
        styles: ['modal_jazz', 'contemporary_modal'],
        modeFamilies: ['aeolian', 'dorian', 'mixolydian', 'ionian'],
        families: ['minor_loop'],
      },
      difficultyProfile: {
        level: 1,
        accidentalComplexity: 1,
        borrowedChordCount: 0,
        alterationComplexity: 0,
      },
      chainTargets: ['aeolian_return_home'],
    },
    {
      id: 'aeolian_bVI_bIII',
      lane: 'aeolian',
      difficulty: 1,
      steps: [
        { roman: 'i7', functionTag: 'tonic', recommendedScaleIds: ['aeolian', 'minor_pentatonic'], colorScaleIds: ['dorian'] },
        { roman: 'bVImaj7', functionTag: 'color', recommendedScaleIds: ['lydian', 'major_pentatonic'], colorScaleIds: ['ionian'] },
        { roman: 'bIIImaj7', functionTag: 'color', recommendedScaleIds: ['ionian', 'major_pentatonic'], colorScaleIds: ['lydian'] },
        { roman: 'bVII7', functionTag: 'dominant', recommendedScaleIds: ['mixolydian'], colorScaleIds: ['aeolian'] },
      ],
      allowedVoicings: ['shell_137', 'closed_7th'],
      rhythmPlan: ['quarters', 'quarters', 'quarters', 'quarters'],
      maxVoiceMotionSemitones: 7,
      tonicCenterStable: true,
      tags: {
        styles: ['contemporary_modal'],
        modeFamilies: ['aeolian', 'lydian', 'ionian', 'mixolydian'],
        families: ['minor_loop'],
      },
      difficultyProfile: {
        level: 1,
        accidentalComplexity: 1,
        borrowedChordCount: 0,
        alterationComplexity: 0,
      },
      chainTargets: ['aeolian_return_home'],
    },
    {
      id: 'aeolian_scalar_lane',
      lane: 'aeolian',
      difficulty: 2,
      steps: [
        { roman: 'i7', functionTag: 'tonic', recommendedScaleIds: ['aeolian', 'minor_pentatonic'], colorScaleIds: ['dorian'] },
        { roman: 'iiø', functionTag: 'passing', recommendedScaleIds: ['locrian'], colorScaleIds: ['aeolian'] },
        { roman: 'bIIImaj7', functionTag: 'color', recommendedScaleIds: ['ionian', 'major_pentatonic'], colorScaleIds: ['lydian'] },
        { roman: 'iv7', functionTag: 'predominant', recommendedScaleIds: ['dorian'], colorScaleIds: ['aeolian'] },
      ],
      allowedVoicings: ['shell_137', 'closed_7th', 'inversion_1'],
      rhythmPlan: ['block_whole', 'charleston', 'charleston', 'quarters'],
      maxVoiceMotionSemitones: 8,
      tonicCenterStable: true,
      tags: {
        styles: ['modal_jazz'],
        modeFamilies: ['aeolian', 'ionian', 'dorian'],
        families: ['scalar'],
      },
      difficultyProfile: {
        level: 2,
        accidentalComplexity: 2,
        borrowedChordCount: 0,
        alterationComplexity: 0,
      },
      chainTargets: ['aeolian_minor_turn'],
    },
    {
      id: 'aeolian_minor_turn',
      lane: 'aeolian',
      difficulty: 2,
      steps: [
        { roman: 'iv7', functionTag: 'predominant', recommendedScaleIds: ['dorian'], colorScaleIds: ['aeolian'] },
        { roman: 'v7', functionTag: 'dominant', recommendedScaleIds: ['phrygian'], colorScaleIds: ['aeolian'] },
        { roman: 'bVImaj7', functionTag: 'color', recommendedScaleIds: ['lydian', 'major_pentatonic'], colorScaleIds: ['ionian'] },
        { roman: 'bVII7', functionTag: 'dominant', recommendedScaleIds: ['mixolydian'], colorScaleIds: ['aeolian'] },
      ],
      allowedVoicings: ['shell_137', 'closed_7th', 'inversion_1'],
      rhythmPlan: ['charleston', 'quarters', 'quarters', 'charleston'],
      maxVoiceMotionSemitones: 9,
      tonicCenterStable: true,
      tags: {
        styles: ['contemporary_modal'],
        modeFamilies: ['dorian', 'phrygian', 'lydian', 'mixolydian'],
        families: ['minor_loop', 'turnaround'],
      },
      difficultyProfile: {
        level: 2,
        accidentalComplexity: 2,
        borrowedChordCount: 0,
        alterationComplexity: 0,
      },
      chainTargets: ['aeolian_return_home'],
    },
    {
      id: 'aeolian_return_home',
      lane: 'aeolian',
      difficulty: 2,
      steps: [
        { roman: 'bIIImaj7', functionTag: 'color', recommendedScaleIds: ['ionian', 'major_pentatonic'], colorScaleIds: ['lydian'] },
        { roman: 'bVII7', functionTag: 'dominant', recommendedScaleIds: ['mixolydian'], colorScaleIds: ['aeolian'] },
        { roman: 'i7', functionTag: 'tonic', recommendedScaleIds: ['aeolian', 'minor_pentatonic'], colorScaleIds: ['dorian'] },
        { roman: 'iv7', functionTag: 'predominant', recommendedScaleIds: ['dorian'], colorScaleIds: ['aeolian'] },
      ],
      allowedVoicings: ['closed_7th', 'inversion_1'],
      rhythmPlan: ['quarters', 'charleston', 'block_whole', 'quarters'],
      maxVoiceMotionSemitones: 9,
      tonicCenterStable: true,
      tags: {
        styles: ['modal_jazz', 'contemporary_modal'],
        modeFamilies: ['ionian', 'mixolydian', 'aeolian', 'dorian'],
        families: ['cadence', 'minor_loop'],
      },
      difficultyProfile: {
        level: 2,
        accidentalComplexity: 2,
        borrowedChordCount: 0,
        alterationComplexity: 0,
      },
      chainTargets: ['aeolian_b67_loop'],
    },
  ],
};
