import type { ContentPack } from './types';

export const ionianStarterPack: ContentPack = {
  id: 'ionian_starter_v1',
  version: 1,
  lane: 'ionian',
  roots: ['C', 'G', 'F'],
  voicings: ['shell_137', 'closed_7th', 'inversion_1'],
  rhythms: ['block_whole', 'quarters', 'charleston'],
  templates: [
    {
      id: 'ionian_scalar_up',
      lane: 'ionian',
      difficulty: 1,
      romanPlan: ['Imaj7', 'ii7', 'iii7', 'IVmaj7'],
      allowedVoicings: ['shell_137', 'closed_7th'],
      rhythmPlan: ['block_whole', 'block_whole', 'block_whole', 'block_whole'],
      maxVoiceMotionSemitones: 5,
      tonicCenterStable: true,
    },
    {
      id: 'ionian_scalar_down',
      lane: 'ionian',
      difficulty: 1,
      romanPlan: ['V7', 'IVmaj7', 'iii7', 'ii7'],
      allowedVoicings: ['shell_137', 'closed_7th'],
      rhythmPlan: ['quarters', 'quarters', 'quarters', 'quarters'],
      maxVoiceMotionSemitones: 6,
      tonicCenterStable: true,
    },
    {
      id: 'ionian_turnaround',
      lane: 'ionian',
      difficulty: 1,
      romanPlan: ['Imaj7', 'vi7', 'ii7', 'V7'],
      allowedVoicings: ['shell_137', 'closed_7th', 'inversion_1'],
      rhythmPlan: ['charleston', 'charleston', 'charleston', 'charleston'],
      maxVoiceMotionSemitones: 6,
      tonicCenterStable: true,
    },
    {
      id: 'ionian_predominant',
      lane: 'ionian',
      difficulty: 1,
      romanPlan: ['Imaj7', 'IVmaj7', 'ii7', 'V7'],
      allowedVoicings: ['shell_137', 'closed_7th', 'inversion_1'],
      rhythmPlan: ['block_whole', 'charleston', 'charleston', 'block_whole'],
      maxVoiceMotionSemitones: 7,
      tonicCenterStable: true,
    },
    {
      id: 'ionian_circle_motion',
      lane: 'ionian',
      difficulty: 2,
      romanPlan: ['iii7', 'vi7', 'ii7', 'V7'],
      allowedVoicings: ['shell_137', 'closed_7th', 'inversion_1'],
      rhythmPlan: ['quarters', 'quarters', 'charleston', 'charleston'],
      maxVoiceMotionSemitones: 8,
      tonicCenterStable: true,
    },
    {
      id: 'ionian_cadence_return',
      lane: 'ionian',
      difficulty: 2,
      romanPlan: ['ii7', 'V7', 'Imaj7', 'vi7'],
      allowedVoicings: ['closed_7th', 'inversion_1'],
      rhythmPlan: ['charleston', 'charleston', 'block_whole', 'quarters'],
      maxVoiceMotionSemitones: 8,
      tonicCenterStable: true,
    },
  ],
};
