import type { ContentPack } from './types';

export const ionianStarterPack: ContentPack = {
  id: 'ionian_starter_v1',
  version: 1,
  lane: 'ionian',
  roots: ['C', 'G', 'F'],
  voicings: ['shell_137', 'closed_7th', 'inversion_1'],
  rhythms: ['block_whole', 'quarters', 'charleston'],
  progressions: [
    {
      id: 'ionian_scalar_up',
      lane: 'ionian',
      difficulty: 1,
      steps: [
        { roman: 'Imaj7', functionTag: 'tonic', recommendedScaleIds: ['ionian', 'major_pentatonic'], colorScaleIds: ['lydian'] },
        { roman: 'ii7', functionTag: 'predominant', recommendedScaleIds: ['dorian'], colorScaleIds: ['major_pentatonic'] },
        { roman: 'iii7', functionTag: 'color', recommendedScaleIds: ['phrygian'], colorScaleIds: ['ionian'] },
        { roman: 'IVmaj7', functionTag: 'predominant', recommendedScaleIds: ['lydian'], colorScaleIds: ['ionian'] },
      ],
      allowedVoicings: ['shell_137', 'closed_7th'],
      rhythmPlan: ['block_whole', 'block_whole', 'block_whole', 'block_whole'],
      maxVoiceMotionSemitones: 5,
      tonicCenterStable: true,
      tags: {
        styles: ['functional_jazz', 'modal_jazz'],
        modeFamilies: ['ionian', 'dorian', 'phrygian', 'lydian'],
        families: ['scalar'],
      },
      difficultyProfile: {
        level: 1,
        accidentalComplexity: 0,
        borrowedChordCount: 0,
        alterationComplexity: 0,
      },
      chainTargets: ['ionian_predominant', 'ionian_circle_motion'],
    },
    {
      id: 'ionian_scalar_down',
      lane: 'ionian',
      difficulty: 1,
      steps: [
        { roman: 'V7', functionTag: 'dominant', recommendedScaleIds: ['mixolydian'], colorScaleIds: ['major_pentatonic'] },
        { roman: 'IVmaj7', functionTag: 'predominant', recommendedScaleIds: ['lydian'], colorScaleIds: ['ionian'] },
        { roman: 'iii7', functionTag: 'color', recommendedScaleIds: ['phrygian'], colorScaleIds: ['ionian'] },
        { roman: 'ii7', functionTag: 'predominant', recommendedScaleIds: ['dorian'], colorScaleIds: ['major_pentatonic'] },
      ],
      allowedVoicings: ['shell_137', 'closed_7th'],
      rhythmPlan: ['quarters', 'quarters', 'quarters', 'quarters'],
      maxVoiceMotionSemitones: 6,
      tonicCenterStable: true,
      tags: {
        styles: ['functional_jazz'],
        modeFamilies: ['mixolydian', 'lydian', 'phrygian', 'dorian'],
        families: ['scalar'],
      },
      difficultyProfile: {
        level: 1,
        accidentalComplexity: 1,
        borrowedChordCount: 0,
        alterationComplexity: 0,
      },
      chainTargets: ['ionian_predominant'],
    },
    {
      id: 'ionian_turnaround',
      lane: 'ionian',
      difficulty: 1,
      steps: [
        { roman: 'Imaj7', functionTag: 'tonic', recommendedScaleIds: ['ionian', 'major_pentatonic'], colorScaleIds: ['lydian'] },
        { roman: 'vi7', functionTag: 'color', recommendedScaleIds: ['aeolian', 'minor_pentatonic'], colorScaleIds: ['dorian'] },
        { roman: 'ii7', functionTag: 'predominant', recommendedScaleIds: ['dorian'], colorScaleIds: ['major_pentatonic'] },
        { roman: 'V7', functionTag: 'dominant', recommendedScaleIds: ['mixolydian'], colorScaleIds: ['major_pentatonic'] },
      ],
      allowedVoicings: ['shell_137', 'closed_7th', 'inversion_1'],
      rhythmPlan: ['charleston', 'charleston', 'charleston', 'charleston'],
      maxVoiceMotionSemitones: 6,
      tonicCenterStable: true,
      tags: {
        styles: ['functional_jazz'],
        modeFamilies: ['ionian', 'aeolian', 'dorian', 'mixolydian'],
        families: ['turnaround', 'cadence'],
      },
      difficultyProfile: {
        level: 1,
        accidentalComplexity: 1,
        borrowedChordCount: 0,
        alterationComplexity: 0,
      },
      chainTargets: ['ionian_cadence_return', 'ionian_predominant', 'ionian_scalar_up'],
    },
    {
      id: 'ionian_predominant',
      lane: 'ionian',
      difficulty: 1,
      steps: [
        { roman: 'Imaj7', functionTag: 'tonic', recommendedScaleIds: ['ionian'], colorScaleIds: ['major_pentatonic'] },
        { roman: 'IVmaj7', functionTag: 'predominant', recommendedScaleIds: ['lydian'], colorScaleIds: ['ionian'] },
        { roman: 'ii7', functionTag: 'predominant', recommendedScaleIds: ['dorian'], colorScaleIds: ['major_pentatonic'] },
        { roman: 'V7', functionTag: 'dominant', recommendedScaleIds: ['mixolydian'], colorScaleIds: ['major_pentatonic'] },
      ],
      allowedVoicings: ['shell_137', 'closed_7th', 'inversion_1'],
      rhythmPlan: ['block_whole', 'charleston', 'charleston', 'block_whole'],
      maxVoiceMotionSemitones: 7,
      tonicCenterStable: true,
      tags: {
        styles: ['functional_jazz'],
        modeFamilies: ['ionian', 'lydian', 'dorian', 'mixolydian'],
        families: ['predominant', 'cadence'],
      },
      difficultyProfile: {
        level: 1,
        accidentalComplexity: 1,
        borrowedChordCount: 0,
        alterationComplexity: 0,
      },
      chainTargets: ['ionian_cadence_return', 'ionian_turnaround', 'ionian_circle_motion'],
    },
    {
      id: 'ionian_circle_motion',
      lane: 'ionian',
      difficulty: 2,
      steps: [
        { roman: 'iii7', functionTag: 'color', recommendedScaleIds: ['phrygian'], colorScaleIds: ['ionian'] },
        { roman: 'vi7', functionTag: 'color', recommendedScaleIds: ['aeolian', 'minor_pentatonic'], colorScaleIds: ['dorian'] },
        { roman: 'ii7', functionTag: 'predominant', recommendedScaleIds: ['dorian'], colorScaleIds: ['major_pentatonic'] },
        { roman: 'V7', functionTag: 'dominant', recommendedScaleIds: ['mixolydian'], colorScaleIds: ['major_pentatonic'] },
      ],
      allowedVoicings: ['shell_137', 'closed_7th', 'inversion_1'],
      rhythmPlan: ['quarters', 'quarters', 'charleston', 'charleston'],
      maxVoiceMotionSemitones: 8,
      tonicCenterStable: true,
      tags: {
        styles: ['functional_jazz'],
        modeFamilies: ['phrygian', 'aeolian', 'dorian', 'mixolydian'],
        families: ['circle_motion', 'cadence'],
      },
      difficultyProfile: {
        level: 2,
        accidentalComplexity: 1,
        borrowedChordCount: 0,
        alterationComplexity: 0,
      },
      chainTargets: ['ionian_cadence_return', 'ionian_turnaround', 'ionian_scalar_down'],
    },
    {
      id: 'ionian_cadence_return',
      lane: 'ionian',
      difficulty: 2,
      steps: [
        { roman: 'ii7', functionTag: 'predominant', recommendedScaleIds: ['dorian'], colorScaleIds: ['major_pentatonic'] },
        { roman: 'V7', functionTag: 'dominant', recommendedScaleIds: ['mixolydian'], colorScaleIds: ['major_pentatonic'] },
        { roman: 'Imaj7', functionTag: 'tonic', recommendedScaleIds: ['ionian'], colorScaleIds: ['lydian'] },
        { roman: 'vi7', functionTag: 'color', recommendedScaleIds: ['aeolian', 'minor_pentatonic'], colorScaleIds: ['dorian'] },
      ],
      allowedVoicings: ['closed_7th', 'inversion_1'],
      rhythmPlan: ['charleston', 'charleston', 'block_whole', 'quarters'],
      maxVoiceMotionSemitones: 8,
      tonicCenterStable: true,
      tags: {
        styles: ['functional_jazz'],
        modeFamilies: ['dorian', 'mixolydian', 'ionian', 'aeolian'],
        families: ['cadence', 'turnaround'],
      },
      difficultyProfile: {
        level: 2,
        accidentalComplexity: 1,
        borrowedChordCount: 0,
        alterationComplexity: 0,
      },
      chainTargets: ['ionian_turnaround', 'ionian_circle_motion', 'ionian_scalar_down'],
    },
  ],
};
