import type { ContentPack } from './types';

export const mixedStarterPack: ContentPack = {
  id: 'mixed_starter_v1',
  version: 1,
  lane: 'ionian_aeolian_mixture',
  roots: ['C', 'G', 'F'],
  voicings: ['shell_137', 'closed_7th', 'inversion_1'],
  rhythms: ['block_whole', 'quarters', 'charleston'],
  templates: [
    {
      id: 'parallel_minor_iv',
      lane: 'ionian_aeolian_mixture',
      difficulty: 1,
      romanPlan: ['Imaj7', 'ivm7', 'bVII7', 'Imaj7'],
      allowedVoicings: ['shell_137', 'closed_7th'],
      rhythmPlan: ['block_whole', 'charleston', 'charleston', 'block_whole'],
      maxVoiceMotionSemitones: 6,
      tonicCenterStable: true,
    },
    {
      id: 'backdoor_bVII',
      lane: 'ionian_aeolian_mixture',
      difficulty: 1,
      romanPlan: ['Imaj7', 'bVImaj7', 'bVII7', 'Imaj7'],
      allowedVoicings: ['shell_137', 'closed_7th', 'inversion_1'],
      rhythmPlan: ['charleston', 'charleston', 'charleston', 'charleston'],
      maxVoiceMotionSemitones: 7,
      tonicCenterStable: true,
    },
    {
      id: 'borrowed_minor_chain',
      lane: 'ionian_aeolian_mixture',
      difficulty: 1,
      romanPlan: ['Imaj7', 'vm7', 'ivm7', 'Imaj7'],
      allowedVoicings: ['shell_137', 'closed_7th'],
      rhythmPlan: ['quarters', 'quarters', 'quarters', 'quarters'],
      maxVoiceMotionSemitones: 7,
      tonicCenterStable: true,
    },
    {
      id: 'ionian_to_borrowed_return',
      lane: 'ionian_aeolian_mixture',
      difficulty: 2,
      romanPlan: ['Imaj7', 'vi7', 'ivm7', 'V7'],
      allowedVoicings: ['shell_137', 'closed_7th', 'inversion_1'],
      rhythmPlan: ['block_whole', 'quarters', 'charleston', 'charleston'],
      maxVoiceMotionSemitones: 8,
      tonicCenterStable: true,
    },
    {
      id: 'double_borrowed_then_home',
      lane: 'ionian_aeolian_mixture',
      difficulty: 2,
      romanPlan: ['Imaj7', 'ivm7', 'bVImaj7', 'bVII7'],
      allowedVoicings: ['closed_7th', 'inversion_1'],
      rhythmPlan: ['charleston', 'charleston', 'quarters', 'quarters'],
      maxVoiceMotionSemitones: 9,
      tonicCenterStable: true,
    },
    {
      id: 'mixed_cadence_return',
      lane: 'ionian_aeolian_mixture',
      difficulty: 2,
      romanPlan: ['bVII7', 'Imaj7', 'ivm7', 'Imaj7'],
      allowedVoicings: ['closed_7th', 'inversion_1'],
      rhythmPlan: ['quarters', 'block_whole', 'charleston', 'charleston'],
      maxVoiceMotionSemitones: 9,
      tonicCenterStable: true,
    },
  ],
};
