import type { ContentPack } from './types';

export const mixedStarterPack: ContentPack = {
  id: 'mixed_starter_v1',
  version: 1,
  lane: 'ionian_aeolian_mixture',
  roots: ['C', 'G', 'F'],
  voicings: ['shell_137', 'closed_7th', 'inversion_1'],
  rhythms: ['block_whole', 'quarters', 'charleston'],
  progressions: [
    {
      id: 'parallel_minor_iv',
      lane: 'ionian_aeolian_mixture',
      difficulty: 1,
      steps: [
        { roman: 'Imaj7', functionTag: 'tonic', recommendedScaleIds: ['ionian', 'major_pentatonic'], colorScaleIds: ['lydian'] },
        { roman: 'ivm7', functionTag: 'color', recommendedScaleIds: ['dorian', 'aeolian'], colorScaleIds: ['minor_pentatonic'] },
        { roman: 'bVII7', functionTag: 'dominant', recommendedScaleIds: ['mixolydian'], colorScaleIds: ['aeolian'] },
        { roman: 'Imaj7', functionTag: 'tonic', recommendedScaleIds: ['ionian'], colorScaleIds: ['lydian'] },
      ],
      allowedVoicings: ['shell_137', 'closed_7th'],
      rhythmPlan: ['block_whole', 'charleston', 'charleston', 'block_whole'],
      maxVoiceMotionSemitones: 6,
      tonicCenterStable: true,
      tags: {
        styles: ['borrowed_color', 'contemporary_modal'],
        modeFamilies: ['ionian', 'aeolian', 'dorian', 'mixolydian'],
        families: ['borrowed'],
      },
      difficultyProfile: {
        level: 1,
        accidentalComplexity: 2,
        borrowedChordCount: 2,
        alterationComplexity: 0,
      },
      chainTargets: ['backdoor_bVII', 'mixed_cadence_return'],
    },
    {
      id: 'backdoor_bVII',
      lane: 'ionian_aeolian_mixture',
      difficulty: 1,
      steps: [
        { roman: 'Imaj7', functionTag: 'tonic', recommendedScaleIds: ['ionian', 'major_pentatonic'], colorScaleIds: ['lydian'] },
        { roman: 'bVImaj7', functionTag: 'color', recommendedScaleIds: ['lydian'], colorScaleIds: ['major_pentatonic'] },
        { roman: 'bVII7', functionTag: 'dominant', recommendedScaleIds: ['mixolydian'], colorScaleIds: ['aeolian'] },
        { roman: 'Imaj7', functionTag: 'tonic', recommendedScaleIds: ['ionian'], colorScaleIds: ['lydian'] },
      ],
      allowedVoicings: ['shell_137', 'closed_7th', 'inversion_1'],
      rhythmPlan: ['charleston', 'charleston', 'charleston', 'charleston'],
      maxVoiceMotionSemitones: 7,
      tonicCenterStable: true,
      tags: {
        styles: ['borrowed_color', 'contemporary_modal'],
        modeFamilies: ['ionian', 'lydian', 'mixolydian', 'aeolian'],
        families: ['borrowed', 'backdoor'],
      },
      difficultyProfile: {
        level: 1,
        accidentalComplexity: 2,
        borrowedChordCount: 2,
        alterationComplexity: 0,
      },
      chainTargets: ['parallel_minor_iv'],
    },
    {
      id: 'borrowed_minor_chain',
      lane: 'ionian_aeolian_mixture',
      difficulty: 1,
      steps: [
        { roman: 'Imaj7', functionTag: 'tonic', recommendedScaleIds: ['ionian'], colorScaleIds: ['major_pentatonic'] },
        { roman: 'vm7', functionTag: 'color', recommendedScaleIds: ['aeolian', 'minor_pentatonic'], colorScaleIds: ['dorian'] },
        { roman: 'ivm7', functionTag: 'color', recommendedScaleIds: ['dorian', 'aeolian'], colorScaleIds: ['minor_pentatonic'] },
        { roman: 'Imaj7', functionTag: 'tonic', recommendedScaleIds: ['ionian'], colorScaleIds: ['lydian'] },
      ],
      allowedVoicings: ['shell_137', 'closed_7th'],
      rhythmPlan: ['quarters', 'quarters', 'quarters', 'quarters'],
      maxVoiceMotionSemitones: 7,
      tonicCenterStable: true,
      tags: {
        styles: ['borrowed_color'],
        modeFamilies: ['ionian', 'aeolian', 'dorian'],
        families: ['borrowed'],
      },
      difficultyProfile: {
        level: 1,
        accidentalComplexity: 2,
        borrowedChordCount: 2,
        alterationComplexity: 0,
      },
      chainTargets: ['ionian_to_borrowed_return'],
    },
    {
      id: 'ionian_to_borrowed_return',
      lane: 'ionian_aeolian_mixture',
      difficulty: 2,
      steps: [
        { roman: 'Imaj7', functionTag: 'tonic', recommendedScaleIds: ['ionian'], colorScaleIds: ['lydian'] },
        { roman: 'vi7', functionTag: 'color', recommendedScaleIds: ['aeolian', 'minor_pentatonic'], colorScaleIds: ['dorian'] },
        { roman: 'ivm7', functionTag: 'color', recommendedScaleIds: ['dorian', 'aeolian'], colorScaleIds: ['minor_pentatonic'] },
        { roman: 'V7', functionTag: 'dominant', recommendedScaleIds: ['mixolydian'], colorScaleIds: ['major_pentatonic'] },
      ],
      allowedVoicings: ['shell_137', 'closed_7th', 'inversion_1'],
      rhythmPlan: ['block_whole', 'quarters', 'charleston', 'charleston'],
      maxVoiceMotionSemitones: 8,
      tonicCenterStable: true,
      tags: {
        styles: ['borrowed_color', 'functional_jazz'],
        modeFamilies: ['ionian', 'aeolian', 'dorian', 'mixolydian'],
        families: ['borrowed', 'cadence'],
      },
      difficultyProfile: {
        level: 2,
        accidentalComplexity: 2,
        borrowedChordCount: 1,
        alterationComplexity: 0,
      },
      chainTargets: ['mixed_cadence_return'],
    },
    {
      id: 'double_borrowed_then_home',
      lane: 'ionian_aeolian_mixture',
      difficulty: 2,
      steps: [
        { roman: 'Imaj7', functionTag: 'tonic', recommendedScaleIds: ['ionian'], colorScaleIds: ['lydian'] },
        { roman: 'ivm7', functionTag: 'color', recommendedScaleIds: ['dorian', 'aeolian'], colorScaleIds: ['minor_pentatonic'] },
        { roman: 'bVImaj7', functionTag: 'color', recommendedScaleIds: ['lydian'], colorScaleIds: ['major_pentatonic'] },
        { roman: 'bVII7', functionTag: 'dominant', recommendedScaleIds: ['mixolydian'], colorScaleIds: ['aeolian'] },
      ],
      allowedVoicings: ['closed_7th', 'inversion_1'],
      rhythmPlan: ['charleston', 'charleston', 'quarters', 'quarters'],
      maxVoiceMotionSemitones: 9,
      tonicCenterStable: true,
      tags: {
        styles: ['borrowed_color', 'contemporary_modal'],
        modeFamilies: ['ionian', 'aeolian', 'dorian', 'lydian', 'mixolydian'],
        families: ['borrowed', 'backdoor'],
      },
      difficultyProfile: {
        level: 2,
        accidentalComplexity: 3,
        borrowedChordCount: 2,
        alterationComplexity: 0,
      },
      chainTargets: ['backdoor_bVII'],
    },
    {
      id: 'mixed_cadence_return',
      lane: 'ionian_aeolian_mixture',
      difficulty: 2,
      steps: [
        { roman: 'bVII7', functionTag: 'dominant', recommendedScaleIds: ['mixolydian'], colorScaleIds: ['aeolian'] },
        { roman: 'Imaj7', functionTag: 'tonic', recommendedScaleIds: ['ionian'], colorScaleIds: ['lydian'] },
        { roman: 'ivm7', functionTag: 'color', recommendedScaleIds: ['dorian', 'aeolian'], colorScaleIds: ['minor_pentatonic'] },
        { roman: 'Imaj7', functionTag: 'tonic', recommendedScaleIds: ['ionian'], colorScaleIds: ['major_pentatonic'] },
      ],
      allowedVoicings: ['closed_7th', 'inversion_1'],
      rhythmPlan: ['quarters', 'block_whole', 'charleston', 'charleston'],
      maxVoiceMotionSemitones: 9,
      tonicCenterStable: true,
      tags: {
        styles: ['borrowed_color', 'contemporary_modal'],
        modeFamilies: ['mixolydian', 'ionian', 'aeolian', 'dorian'],
        families: ['borrowed', 'cadence'],
      },
      difficultyProfile: {
        level: 2,
        accidentalComplexity: 3,
        borrowedChordCount: 2,
        alterationComplexity: 0,
      },
      chainTargets: ['parallel_minor_iv'],
    },
  ],
};
